# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
# 放預設值(測試站)的 token

pay2go_merchant_id: "12046344"
pay2go_hash_key: "VZevFPfd0xlnMSHwcz9bMlqEFV95LWzG"
pay2go_hash_iv: "VNcADsOE0a2M2Jif"
pay2go_service_url: "https://capi.pay2go.com/MPG/mpg_gateway"
aws_access_key_id: "xxx"
aws_secret_access_key: "yyy"

# 放正式站的 token

# 若尚未有正式站的 token 可以不用輸入

# heroku 那裡仍是在做金流功能測試

production:
  pay2go_merchant_id: "12046344"
  pay2go_hash_key: "VZevFPfd0xlnMSHwcz9bMlqEFV95LWzG"
  pay2go_hash_iv: "VNcADsOE0a2M2Jif"
  pay2go_service_url: "https://api.pay2go.com/MPG/mpg_gateway"
  aws_access_key_id: "AKIAJK7KTJSUNW6FGVDA"
  aws_secret_access_key: "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"
